version: "3.9"

services:
  postgres:
    container_name: simplebank-postgres
    image: postgres:16.2
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256

    networks:
      - simplebank_network
    volumes:
      - $HOME/data/postgresql/simplebank:/var/lib/postgresql/data
    ports:
      - "$DB_PORT:5432"

  simplebank:
    container_name: simplebank-api-core
    build:
      context: .
      dockerfile: Dockerfile
      # target: builder
    env_file:
      - .env
    # ports:
    #   - "$PORT:$PORT"
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      # - /usr/src/app/go.mod
    networks:
      - simplebank_network
    command: /usr/src/app/main # overrides CMD from dockerfile

networks:
  simplebank_network:
    driver: bridge
