version: "3.9"

services:
  postgres:
    container_name: simplebank-postgres
    image: postgres:16.2
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256

    networks:
      - simplebank_api_network
    volumes:
      - $HOME/data/postgresql/simplebank:/var/lib/postgresql/data
    ports:
      - "$DB_PORT:5432"

  # adminer:
  #   image: adminer:4.8.1
  #   container_name: simplebank-adminer
  #   depends_on:
  #     - postgres
  #   networks:
  #     - simplebank_api_network
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     ADMINER_DEFAULT_SERVER: postgres
  #     ADMINER_DESIGN: galkaev
  #   env_file:
  #     - .env

  # simplebank:
  #   container_name: simplebank-api-core
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: base
  #   env_file:
  #     - .env
  #   ports:
  #     - "$PORT:$PORT"
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - .:/usr/src/app # any change to base folder should be reflected
  #     - /usr/src/app/node_modules
  #   networks:
  #     - simplebank_api_network
  #   command: yarn dev # overrides CMD from dockerfile

networks:
  simplebank_api_network:
    driver: bridge