name: CI Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.2
        env:
          POSTGRES_PASSWORD: SimpleBank1234
          POSTGRES_DB: simplebank
          POSTGRES_USER: simplebank
          POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20'
        id: go

      - name: Create env file
        run: |
            echo "${{ secrets.TEST_ENV_FILE }}" > .env
            cat .env

      - name: Install golang-migrate
        run: | 
            curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.1/migrate.linux-amd64.tar.gz | tar xvz
            sudo mv migrate /usr/bin
            which migrate

      - name: Run DB Migrations
        run: make migrate

      - name: Test
        run: make test
